import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';

export const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        backgroundColor: '#17171E',
    },
    title: {
        fontFamily: 'Hakgyoansim',
        fontSize: RFValue(44),
        marginBottom: 20,
        color: '#D6DEFD',
    },
    signUpLabel: {
        color: '#7A7E9B',
        fontFamily: 'Pretendard4',
        alignSelf: 'flex-start',
        fontSize: RFValue(16),
        marginBottom: 10,
    },
    emailContainer: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        alignContent: 'center',
        justifyContent: 'space-between',
    },
    inputEmail: {
        fontFamily: 'Pretendard4',
        width: '75%',
        height: 50,
        backgroundColor: '#202027',
        borderWidth: 1,
        borderColor: '#69728F',
        color: '#D6DEFD',
        borderRadius: 10,
        paddingHorizontal: 15,
        marginBottom: 15,
    },
    authButton: {
        width: '23%',
        height: 50,
        backgroundColor: '#D6DEFD',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    authText: {
        color: '#69728F',
        fontFamily: 'Pretendard7',
        fontSize: RFValue(14),
    },
    input: {
        fontFamily: 'Pretendard4',
        width: '100%',
        height: 50,
        backgroundColor: '#202027',
        borderWidth: 1,
        borderColor: '#69728F',
        color: '#D6DEFD',
        borderRadius: 10,
        paddingHorizontal: 15,
        marginBottom: 15,
    },
    button: {
        width: '100%',
        height: 50,
        backgroundColor: '#D6DEFD',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 20,
    },
    buttonText: {
        color: '#69728F',
        fontFamily: 'Pretendard7',
        fontSize: RFValue(16),
    },
});
