import { StyleSheet } from "react-native";
import { RFValue } from 'react-native-responsive-fontsize';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        backgroundColor: '#17171E',
    },
    title: {
        fontFamily: 'Hakgyoansim',
        fontSize: RFValue(44),
        color: '#D6DEFD',
        marginBottom: 30,
    },
    loginLabel: {
        fontFamily: 'Pretendard4',
        color: '#7A7E9B',
        alignSelf: 'flex-start',
        fontSize: RFValue(16),
        marginBottom: 10,
    },
    input: {
        fontFamily: 'Pretendard4',
        width: '100%',
        height: 50,
        backgroundColor: '#202027',
        borderWidth: 1,
        borderColor: '#69728F',
        color: '#D6DEFD',
        borderRadius: 10,
        paddingHorizontal: 15,
        marginBottom: 10,
    },
    emailCheckButton: {
        backgroundColor: '#4B72FF',
        paddingVertical: 10,
        borderRadius: 8,
        alignItems: 'center',
        marginBottom: 12,
    },
    emailCheckButtonText: {
        color: '#fff',
        fontWeight: 'bold',
    },
    verificationContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 12,
    },
    verifyButton: {
        backgroundColor: '#28A745',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        justifyContent: 'center',
    },
    verifyButtonText: {
        color: '#fff',
        fontWeight: 'bold',
    },
    passwordContainer: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#202027',
        borderWidth: 1,
        borderColor: '#69728F',
        borderRadius: 10,
        paddingHorizontal: 15,
        marginBottom: 10,
    },
    inputPassword: {
        flex: 1,
        height: 50,
        fontFamily: 'Pretendard4',
        color: '#D6DEFD',
    },
    loginButton: {
        width: '100%',
        height: 50,
        backgroundColor: '#D6DEFD',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    loginButtonText: {
        fontFamily: 'Pretendard7',
        color: '#69728F',
        fontSize: RFValue(16),
    },
    signUpContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    signUpLabelText: {
        fontFamily: 'Pretendard6',
        fontSize: RFValue(12),
        color: '#69728F',
    },
    signUpText: {
        fontFamily: 'Pretendard8',
        fontSize: RFValue(12),
        color: '#989BD2',
    },
    bottomRowContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '90%',
      paddingHorizontal: 10,
      marginTop: 10,
    },
    autoLoginContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 10,  
    },
    autoLoginLabel: {
        color: '#D6DEFD',
        marginRight: 8,  
        marginBottom: 4,
        fontSize: 15,
    },
    autoLoginSwitch: {
      transform: [{ scaleX: 0.9 }, { scaleY: 0.9 }],
    },
    resetText: {
      color: '#9CB1FF',      
      textDecorationLine: 'underline',
      fontSize: 15,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalBox: {
      width: '85%',
      backgroundColor: '#1C1C1E',
      padding: 20,
      borderRadius: 12,
    },
    modalTitle: {
      fontSize: 18,
      color: '#fff',
      marginBottom: 10,
      fontWeight: 'bold',
    },
    modalInput: {
      borderWidth: 1,
      borderColor: '#ccc',
      padding: 10,
      marginTop: 10,
      color: '#fff',
      borderRadius: 8,
    },
    modalButton: {
      backgroundColor: '#6F88FF',
      padding: 10,
      marginTop: 10,
      alignItems: 'center',
      borderRadius: 8,
    },
    modalButtonText: {
      color: '#fff',
      fontWeight: 'bold',
    },
    modalClose: {
      marginTop: 10,
      alignItems: 'center',
    },
    modalCloseText: {
      color: '#ccc',
      fontSize: 13,
    },

});
